In [200]:
import pandas as pd
import numpy as np

# Selecting series data

In [203]:
a=np.arange(1,15,1)

In [204]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [205]:
a[6:14]

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
a[1:12:2]

array([ 2,  4,  6,  8, 10, 12])

In [65]:
a[[6,10,12]]

array([ 7, 11, 13])

In [66]:
b=np.array(np.matrix('1,2,3,4;5,6,7,8'))

In [67]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [206]:
b[1][2]

7

In [68]:
b[0][1]

2

In [208]:
    University = pd.read_csv('data1/University.csv', index_col='INSTNM')
country = University['country']
country

INSTNM
University of Oxford                England
University of Cambridge             England
Stanford University              California
                                  ...      
University College London    United Kingdom
The University of Chicago     United States
Princeton University          United States
Name: country, Length: 10, dtype: object

In [209]:
country.iloc[2]

'California'

In [210]:
country.iloc[[1,5,7]]


INSTNM
University of Cambridge             England
Imperial College London             England
University College London    United Kingdom
Name: country, dtype: object

In [212]:
country.iloc[1:10:3]

INSTNM
University of Cambridge             England
Harvard University            United States
University College London    United Kingdom
Name: country, dtype: object

In [95]:
country.loc['Massachusetts Institute of Technology']

'United States'

In [213]:
country.loc['University of Oxford':'Princeton University':2]

INSTNM
University of Oxford                        England
Stanford University                      California
Harvard University                    United States
California Institute of Technology       California
The University of Chicago             United States
Name: country, dtype: object

In [214]:
country.loc['Princeton University':'University of Oxford':-4]

INSTNM
Princeton University       United States
Imperial College London          England
University of Cambridge          England
Name: country, dtype: object

In [215]:
pd.options.display.max_rows = 6


In [216]:
University


country   UGDS  UGDS_WHITE  UGDS_BLACK  \
INSTNM                                                                     
University of Oxford              England   4206      0.0333      0.9353   
University of Cambridge           England  11383      0.5922      0.2600   
Stanford University            California    291      0.2990      0.4192   
...                                   ...    ...         ...         ...   
University College London  United Kingdom   2991      0.7823      0.1200   
The University of Chicago   United States   4304      0.5328      0.3376   
Princeton University        United States  20514      0.8507      0.0704   

                           UGDS_HISP  UGDS_ASIAN  UGDS_AIAN  UGDS_NHPI  \
INSTNM                                                                   
University of Oxford          0.0055      0.0019     0.0024     0.0019   
University of Cambridge       0.0283      0.0518     0.0022     0.0007   
Stanford University           0.0069      0.0034     0.0000     0.0000   
...                              ...         ...        ...        ...   
University College London     0.0191      0.0053     0.0157     0.0010   
The University of Chicago     0.0074      0.0221     0.0044     0.0016   
Princeton University          0.0248      0.0227     0.0074     0.0000   

                           UGDS_2MOR  UGDS_NRA  UGDS_UNKN  
INSTNM                                                     
University of Oxford          0.0000    0.0059     0.0138  
University of Cambridge       0.0368    0.0179     0.0100  
Stanford University           0.0000    0.0000     0.2715  
...                              ...       ...        ...  
University College London     0.0174    0.0057     0.0334  
The University of Chicago     0.0297    0.0397     0.0246  
Princeton University          0.0000    0.0100     0.0140  

[10 rows x 11 columns]

In [141]:
University.iloc[6]

country       California
UGDS                1592
UGDS_WHITE        0.7255
UGDS_BLACK        0.2613
                 ...    
UGDS_NHPI              0
UGDS_2MOR              0
UGDS_NRA               0
UGDS_UNKN         0.0019
Name: California Institute of Technology, Length: 11, dtype: object

In [217]:
University.loc['University College London']

country       United Kingdom
UGDS                    2991
UGDS_WHITE            0.7823
                   ...      
UGDS_2MOR             0.0174
UGDS_NRA              0.0057
UGDS_UNKN             0.0334
Name: University College London, Length: 11, dtype: object

In [218]:
University.iloc[[3,5,9]]

country   UGDS  UGDS_WHITE  \
INSTNM                                                                    
Massachusetts Institute of Technology  United States   5451      0.6988   
Imperial College London                      England  29851      0.7825   
Princeton University                   United States  20514      0.8507   

                                       UGDS_BLACK  UGDS_HISP  UGDS_ASIAN  \
INSTNM                                                                     
Massachusetts Institute of Technology      0.1255     0.0382      0.0376   
Imperial College London                    0.1119     0.0348      0.0106   
Princeton University                       0.0704     0.0248      0.0227   

                                       UGDS_AIAN  UGDS_NHPI  UGDS_2MOR  \
INSTNM                                                                   
Massachusetts Institute of Technology     0.0143     0.0002     0.0172   
Imperial College London                   0.0038     0.0009     0.0261   
Princeton University                      0.0074     0.0000     0.0000   

                                       UGDS_NRA  UGDS_UNKN  
INSTNM                                                      
Massachusetts Institute of Technology    0.0332     0.0350  
Imperial College London                  0.0268     0.0026  
Princeton University                     0.0100     0.0140

In [219]:
labels = ['Massachusetts Institute of Technology',
          'Imperial College London',
          'Princeton University']
University.loc[labels]

country   UGDS  UGDS_WHITE  \
INSTNM                                                                    
Massachusetts Institute of Technology  United States   5451      0.6988   
Imperial College London                      England  29851      0.7825   
Princeton University                   United States  20514      0.8507   

                                       UGDS_BLACK  UGDS_HISP  UGDS_ASIAN  \
INSTNM                                                                     
Massachusetts Institute of Technology      0.1255     0.0382      0.0376   
Imperial College London                    0.1119     0.0348      0.0106   
Princeton University                       0.0704     0.0248      0.0227   

                                       UGDS_AIAN  UGDS_NHPI  UGDS_2MOR  \
INSTNM                                                                   
Massachusetts Institute of Technology     0.0143     0.0002     0.0172   
Imperial College London                   0.0038     0.0009     0.0261   
Princeton University                      0.0074     0.0000     0.0000   

                                       UGDS_NRA  UGDS_UNKN  
INSTNM                                                      
Massachusetts Institute of Technology    0.0332     0.0350  
Imperial College London                  0.0268     0.0026  
Princeton University                     0.0100     0.0140

In [221]:
University.iloc[1:6]

country   UGDS  UGDS_WHITE  \
INSTNM                                                                    
University of Cambridge                      England  11383      0.5922   
Stanford University                       California    291      0.2990   
Massachusetts Institute of Technology  United States   5451      0.6988   
Harvard University                     United States   4811      0.0158   
Imperial College London                      England  29851      0.7825   

                                       UGDS_BLACK  UGDS_HISP  UGDS_ASIAN  \
INSTNM                                                                     
University of Cambridge                    0.2600     0.0283      0.0518   
Stanford University                        0.4192     0.0069      0.0034   
Massachusetts Institute of Technology      0.1255     0.0382      0.0376   
Harvard University                         0.9208     0.0121      0.0019   
Imperial College London                    0.1119     0.0348      0.0106   

                                       UGDS_AIAN  UGDS_NHPI  UGDS_2MOR  \
INSTNM                                                                   
University of Cambridge                   0.0022     0.0007     0.0368   
Stanford University                       0.0000     0.0000     0.0000   
Massachusetts Institute of Technology     0.0143     0.0002     0.0172   
Harvard University                        0.0010     0.0006     0.0098   
Imperial College London                   0.0038     0.0009     0.0261   

                                       UGDS_NRA  UGDS_UNKN  
INSTNM                                                      
University of Cambridge                  0.0179     0.0100  
Stanford University                      0.0000     0.2715  
Massachusetts Institute of Technology    0.0332     0.0350  
Harvard University                       0.0243     0.0137  
Imperial College London                  0.0268     0.0026

In [150]:
start = 'University of Cambridge'
stop = 'The University of Chicago'
University.loc[start:stop]

country   UGDS  UGDS_WHITE  \
INSTNM                                                                     
University of Cambridge                       England  11383      0.5922   
Stanford University                        California    291      0.2990   
Massachusetts Institute of Technology   United States   5451      0.6988   
Harvard University                      United States   4811      0.0158   
Imperial College London                       England  29851      0.7825   
California Institute of Technology         California   1592      0.7255   
University College London              United Kingdom   2991      0.7823   
The University of Chicago               United States   4304      0.5328   

                                       UGDS_BLACK  UGDS_HISP  UGDS_ASIAN  \
INSTNM                                                                     
University of Cambridge                    0.2600     0.0283      0.0518   
Stanford University                        0.4192     0.0069      0.0034   
Massachusetts Institute of Technology      0.1255     0.0382      0.0376   
Harvard University                         0.9208     0.0121      0.0019   
Imperial College London                    0.1119     0.0348      0.0106   
California Institute of Technology         0.2613     0.0044      0.0025   
University College London                  0.1200     0.0191      0.0053   
The University of Chicago                  0.3376     0.0074      0.0221   

                                       UGDS_AIAN  UGDS_NHPI  UGDS_2MOR  \
INSTNM                                                                   
University of Cambridge                   0.0022     0.0007     0.0368   
Stanford University                       0.0000     0.0000     0.0000   
Massachusetts Institute of Technology     0.0143     0.0002     0.0172   
Harvard University                        0.0010     0.0006     0.0098   
Imperial College London                   0.0038     0.0009     0.0261   
California Institute of Technology        0.0044     0.0000     0.0000   
University College London                 0.0157     0.0010     0.0174   
The University of Chicago                 0.0044     0.0016     0.0297   

                                       UGDS_NRA  UGDS_UNKN  
INSTNM                                                      
University of Cambridge                  0.0179     0.0100  
Stanford University                      0.0000     0.2715  
Massachusetts Institute of Technology    0.0332     0.0350  
Harvard University                       0.0243     0.0137  
Imperial College London                  0.0268     0.0026  
California Institute of Technology       0.0000     0.0019  
University College London                0.0057     0.0334  
The University of Chicago                0.0397     0.0246

# Selecting DataFrame rows and columns simultaneously

In [152]:
University.iloc[:3, :4]

country   UGDS  UGDS_WHITE  UGDS_BLACK
INSTNM                                                            
University of Oxford        England   4206      0.0333      0.9353
University of Cambridge     England  11383      0.5922      0.2600
Stanford University      California    291      0.2990      0.4192

In [154]:
University.loc[:'Stanford University', :'UGDS_BLACK']

country   UGDS  UGDS_WHITE  UGDS_BLACK
INSTNM                                                            
University of Oxford        England   4206      0.0333      0.9353
University of Cambridge     England  11383      0.5922      0.2600
Stanford University      California    291      0.2990      0.4192

In [222]:
University.iloc[:, [4,6]]

UGDS_HISP  UGDS_AIAN
INSTNM                                         
University of Oxford          0.0055     0.0024
University of Cambridge       0.0283     0.0022
Stanford University           0.0069     0.0000
...                              ...        ...
University College London     0.0191     0.0157
The University of Chicago     0.0074     0.0044
Princeton University          0.0248     0.0074

[10 rows x 2 columns]

In [223]:
University.loc[: ,['UGDS_HISP','UGDS_BLACK']]

UGDS_HISP  UGDS_BLACK
INSTNM                                          
University of Oxford          0.0055      0.9353
University of Cambridge       0.0283      0.2600
Stanford University           0.0069      0.4192
...                              ...         ...
University College London     0.0191      0.1200
The University of Chicago     0.0074      0.3376
Princeton University          0.0248      0.0704

[10 rows x 2 columns]

In [224]:
University.iloc[[2,4, 5], [4,7, 9]]

UGDS_HISP  UGDS_NHPI  UGDS_NRA
INSTNM                                                 
Stanford University         0.0069     0.0000    0.0000
Harvard University          0.0121     0.0006    0.0243
Imperial College London     0.0348     0.0009    0.0268

In [225]:
rows = ['California Institute of Technology', 'Massachusetts Institute of Technology']
columns = ['UGDS_BLACK', 'UGDS_NHPI']
University.loc[rows, columns]

UGDS_BLACK  UGDS_NHPI
INSTNM                                                      
California Institute of Technology         0.2613     0.0000
Massachusetts Institute of Technology      0.1255     0.0002

In [226]:
University.iloc[5, -4]

0.0009

In [168]:
University.loc['California Institute of Technology', 'UGDS_NHPI']

0.0

In [170]:
University.iloc[10:1:-2, 5]

INSTNM
Princeton University                     0.0227
University College London                0.0053
Imperial College London                  0.0106
Massachusetts Institute of Technology    0.0376
Name: UGDS_ASIAN, dtype: float64

In [176]:
start = 'Princeton University'
stop = 'University of Oxford'
University.loc[start:stop:-1, 'UGDS_BLACK'].head()

INSTNM
Princeton University                  0.0704
The University of Chicago             0.3376
University College London             0.1200
California Institute of Technology    0.2613
Imperial College London               0.1119
Name: UGDS_BLACK, dtype: float64

# Slicing Lexicographically

In [230]:
University= pd.read_csv('data1/University.csv', index_col='INSTNM')


In [231]:
University=University.sort_index()

In [232]:
University.head()

country   UGDS  UGDS_WHITE  \
INSTNM                                                                    
California Institute of Technology        California   1592      0.7255   
Harvard University                     United States   4811      0.0158   
Imperial College London                      England  29851      0.7825   
Massachusetts Institute of Technology  United States   5451      0.6988   
Princeton University                   United States  20514      0.8507   

                                       UGDS_BLACK  UGDS_HISP  UGDS_ASIAN  \
INSTNM                                                                     
California Institute of Technology         0.2613     0.0044      0.0025   
Harvard University                         0.9208     0.0121      0.0019   
Imperial College London                    0.1119     0.0348      0.0106   
Massachusetts Institute of Technology      0.1255     0.0382      0.0376   
Princeton University                       0.0704     0.0248      0.0227   

                                       UGDS_AIAN  UGDS_NHPI  UGDS_2MOR  \
INSTNM                                                                   
California Institute of Technology        0.0044     0.0000     0.0000   
Harvard University                        0.0010     0.0006     0.0098   
Imperial College London                   0.0038     0.0009     0.0261   
Massachusetts Institute of Technology     0.0143     0.0002     0.0172   
Princeton University                      0.0074     0.0000     0.0000   

                                       UGDS_NRA  UGDS_UNKN  
INSTNM                                                      
California Institute of Technology       0.0000     0.0019  
Harvard University                       0.0243     0.0137  
Imperial College London                  0.0268     0.0026  
Massachusetts Institute of Technology    0.0332     0.0350  
Princeton University                     0.0100     0.0140

In [233]:
pd.options.display.max_rows = 6

In [238]:
University.loc['Un':'uk']

country   UGDS  UGDS_WHITE  UGDS_BLACK  \
INSTNM                                                                     
University College London  United Kingdom   2991      0.7823      0.1200   
University of Cambridge           England  11383      0.5922      0.2600   
University of Oxford              England   4206      0.0333      0.9353   

                           UGDS_HISP  UGDS_ASIAN  UGDS_AIAN  UGDS_NHPI  \
INSTNM                                                                   
University College London     0.0191      0.0053     0.0157     0.0010   
University of Cambridge       0.0283      0.0518     0.0022     0.0007   
University of Oxford          0.0055      0.0019     0.0024     0.0019   

                           UGDS_2MOR  UGDS_NRA  UGDS_UNKN  
INSTNM                                                     
University College London     0.0174    0.0057     0.0334  
University of Cambridge       0.0368    0.0179     0.0100  
University of Oxford          0.0000    0.0059     0.0138

In [239]:
University = University.sort_index(ascending=False)
University.index.is_monotonic_decreasing

True

In [240]:
University.loc['U':'B']

country   UGDS  UGDS_WHITE  \
INSTNM                                                                 
The University of Chicago           United States   4304      0.5328   
Stanford University                    California    291      0.2990   
Princeton University                United States  20514      0.8507   
...                                           ...    ...         ...   
Imperial College London                   England  29851      0.7825   
Harvard University                  United States   4811      0.0158   
California Institute of Technology     California   1592      0.7255   

                                    UGDS_BLACK  UGDS_HISP  UGDS_ASIAN  \
INSTNM                                                                  
The University of Chicago               0.3376     0.0074      0.0221   
Stanford University                     0.4192     0.0069      0.0034   
Princeton University                    0.0704     0.0248      0.0227   
...                                        ...        ...         ...   
Imperial College London                 0.1119     0.0348      0.0106   
Harvard University                      0.9208     0.0121      0.0019   
California Institute of Technology      0.2613     0.0044      0.0025   

                                    UGDS_AIAN  UGDS_NHPI  UGDS_2MOR  UGDS_NRA  \
INSTNM                                                                          
The University of Chicago              0.0044     0.0016     0.0297    0.0397   
Stanford University                    0.0000     0.0000     0.0000    0.0000   
Princeton University                   0.0074     0.0000     0.0000    0.0100   
...                                       ...        ...        ...       ...   
Imperial College London                0.0038     0.0009     0.0261    0.0268   
Harvard University                     0.0010     0.0006     0.0098    0.0243   
California Institute of Technology     0.0044     0.0000     0.0000    0.0000   

                                    UGDS_UNKN  
INSTNM                                         
The University of Chicago              0.0246  
Stanford University                    0.2715  
Princeton University                   0.0140  
...                                       ...  
Imperial College London                0.0026  
Harvard University                     0.0137  
California Institute of Technology     0.0019  

[7 rows x 11 columns]